LocalSocket /var/run/clamav/clamd.sock
DatabaseDirectory /var/lib/clamav
Foreground yes
LogFile /proc/self/fd/2
LogVerbose no
LogTime no
StreamMaxLength 500M
MaxScanSize 200M
MaxFileSize 200M
MaxRecursion 10
MaxFiles 1000
